[package]
name = "spookylock-sys"
version = "0.1.1"
authors = ["toshokan <toshokan@shojigate.net>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[build-dependencies]
bindgen = "^0.52"
cc = "1.0"

[dependencies]
libc = "0.2.66"
