[package]
name = "spookylock"
version = "0.1.0"
authors = ["toshokan <toshokan@shojigate.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spookylock-sys = { path = "../spookylock-sys" }
termion = "1.5.4"
cursive = { version = "^0.13", features = ["termion-backend"], default-features = false }
stream-switch = { path = "../stream-switch" }
pam = "^0.7"
