name: build-release

on:
  release:
    types:
      - created
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
	apt update
	apt install -y libpam0g libpam0g-dev
        cargo build --release --verbose
        tar -cf spookylock-linux.tar.gz target/release/spookylock target/release/spooklock-interface
    - name: Upload Build
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./spookylock-linux.tar.gz
        asset_name: spookylock-linux.tar.gz
        asset_content_type: application/gzip
